# ksops generator - decrypts SOPS-encrypted secrets
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: onepassword-credentials-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - onepassword-credentials.sops.yaml
