{
 "title": "Envoy Global",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [
  "Data Plane",
  "envoy-gateway"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pod) (envoy_server_uptime{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_heap_size{namespace=~\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_allocated{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "DownStream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[5m]))",
     "legendFormat": "Envoy HTTP Downstream Rq total"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_http_downstream_cx_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(envoy_http_downstream_rq_time_bucket[5m])))",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(envoy_http_downstream_rq_time_bucket[5m])))",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(envoy_http_downstream_rq_time_bucket[5m])))",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_listener_downstream_cx_active{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "TCP Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_tcp_downstream_cx_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "TCP Downstream Bytes Rx/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_tcp_downstream_cx_rx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "TCP Downstream Bytes Tx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_tcp_downstream_cx_tx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "UpStream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream RPS",
   "type": "timeseries",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_cluster_upstream_rq_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{namespace=~\"$Namespace\",}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$Namespace\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$Namespace\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$Namespace\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 50% "
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Upstream Bytes Rx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_cluster_upstream_cx_rx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Upstream Bytes Tx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_cluster_upstream_cx_tx_bytes_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Upstream Response Codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream 2xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"2\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"3\"}[5m]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint Percentage Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\"}) by (namespace) / avg(envoy_cluster_membership_total{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_cluster_membership_total{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_cluster_membership_healthy{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (envoy_cluster_membership_total{namespace=~\"$Namespace\"}) - sum by(namespace) (envoy_cluster_membership_healthy{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "TLS Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "TLS Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (envoy_tls_certificate) ((envoy_listener_ssl_certificate_expiration_unix_time_seconds{namespace=~\"$Namespace\"} - time()) / 86400)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}