{{- if .Values.onePasswordItemPath }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: duckdns-token
  namespace: {{ .Values.namespace }}
spec:
  itemPath: {{ .Values.onePasswordItemPath | quote }}
{{- end }}
