{{- if .Values.kiali.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiali
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.kiali.host }}
spec:
  ingressClassName: {{ .Values.kiali.ingressClassName }}
  rules:
    - host: {{ .Values.kiali.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiali
                port:
                  number: 20001
  tls:
    - secretName: kiali-tls
      hosts:
        - {{ .Values.kiali.host }}
{{- end }}
