{{- if .Values.cloudflare.enabled }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token
  namespace: {{ .Values.namespace }}
spec:
  itemPath: {{ .Values.cloudflare.onePasswordItemPath | quote }}
{{- end }}
{{- if .Values.oidc.enabled }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: google-oauth-credentials
  namespace: {{ .Values.namespace }}
spec:
  itemPath: {{ .Values.oidc.googleOAuthPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: oidc-session-key
  namespace: {{ .Values.namespace }}
spec:
  itemPath: {{ .Values.oidc.sessionKeyPath | quote }}
{{- end }}
