{{- if .Values.homeassistant.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://oci.trueforge.org/truecharts
    chart: home-assistant
    targetRevision: {{ .Values.homeassistant.chart.version }}
    helm:
      releaseName: home-assistant
      values: |
        {{- if .Values.homeassistant.workload }}
        workload:
          {{- toYaml .Values.homeassistant.workload | nindent 10 }}
        {{- end }}

        {{- if .Values.homeassistant.podOptions }}
        podOptions:
          {{- toYaml .Values.homeassistant.podOptions | nindent 10 }}
        {{- end }}

        {{- if .Values.homeassistant.persistence }}
        persistence:
          {{- toYaml .Values.homeassistant.persistence | nindent 10 }}
        {{- end }}

        {{- if .Values.homeassistant.ingress }}
        ingress:
          {{- toYaml .Values.homeassistant.ingress | nindent 10 }}
        {{- end }}

        {{- if .Values.homeassistant.TZ }}
        TZ: {{ .Values.homeassistant.TZ | quote }}
        {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.homeassistant.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
