{{- if .Values.radarr.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.radarr.chart.repo }}
    targetRevision: {{ .Values.radarr.chart.version }}
    helm:
      releaseName: radarr
      values: |
        {{- if .Values.radarr.workload }}
        workload:
          {{- toYaml .Values.radarr.workload | nindent 10 }}
        {{- end }}

        {{- if .Values.radarr.persistence }}
        persistence:
          {{- toYaml .Values.radarr.persistence | nindent 10 }}
        {{- end }}

        {{- if .Values.radarr.ingress }}
        ingress:
          {{- toYaml .Values.radarr.ingress | nindent 10 }}
        {{- end }}

        {{- if .Values.radarr.TZ }}
        TZ: {{ .Values.radarr.TZ | quote }}
        {{- end }}

        {{- if .Values.radarr.securityContext }}
        securityContext:
          {{- toYaml .Values.radarr.securityContext | nindent 10 }}
        {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.radarr.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
