{{- if .Values.sonarr.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.sonarr.chart.repo }}
    chart: {{ .Values.sonarr.chart.name }}
    targetRevision: {{ .Values.sonarr.chart.version }}
    helm:
      releaseName: sonarr
      values: |
        {{- if .Values.sonarr.workload }}
        workload:
          {{- toYaml .Values.sonarr.workload | nindent 10 }}
        {{- end }}

        {{- if .Values.sonarr.persistence }}
        persistence:
          {{- toYaml .Values.sonarr.persistence | nindent 10 }}
        {{- end }}

        {{- if .Values.sonarr.ingress }}
        ingress:
          {{- toYaml .Values.sonarr.ingress | nindent 10 }}
        {{- end }}

        {{- if .Values.sonarr.TZ }}
        TZ: {{ .Values.sonarr.TZ | quote }}
        {{- end }}

        {{- if .Values.sonarr.securityContext }}
        securityContext:
          {{- toYaml .Values.sonarr.securityContext | nindent 10 }}
        {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.sonarr.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
