#!/usr/bin/env -S deno test
/**
 * Unit tests for the pure logic in prod-readonly.ts. Nothing here talks to
 * 1Password, Tailscale or a cluster.
 *
 *   deno test scripts/prod-readonly_test.ts
 */

import { assert, assertEquals, assertThrows } from "jsr:@std/assert@^1";
import { parse as parseYaml } from "jsr:@std/yaml@^1";
import {
  argocdDiffCmd,
  checkToken,
  DEFAULT_ARGOCD_TOKEN_REF,
  DEFAULT_CONTEXT,
  DEFAULT_HOSTNAME,
  DEFAULT_TOKEN_REF,
  defaultKubeconfigPath,
  domainFromEnvFile,
  formatTable,
  isMainKubeconfig,
  isRowHealthy,
  type KubeconfigInput,
  kubeconfigPreview,
  kubectlStatusCmd,
  parseArgs,
  proxyServerUrl,
  redact,
  REDACTED,
  renderKubeconfig,
  statusRows,
  tailnetDomain,
  UsageError,
} from "./prod-readonly.ts";

// A syntactically valid (unsigned, fake) JWT. Assembled at runtime so secret
// scanners (gitleaks jwt / generic-api-key) do not mistake the fixture for a
// leaked token; checkToken() only needs the three-segment base64url shape.
const b64url = (s: string): string =>
  btoa(s).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
const TOKEN = [
  b64url('{"alg":"none"}'),
  b64url('{"sub":"system:serviceaccount:agent-access:agent-readonly"}'),
  b64url("signature-fake"),
].join(".");
const ENV = { home: "/home/agent" };

function input(token = TOKEN): KubeconfigInput {
  return {
    server: "https://tailscale-operator-homelab.tail1234.ts.net",
    token,
    context: DEFAULT_CONTEXT,
    user: "agent-readonly",
    namespace: "argocd",
  };
}

Deno.test("renderKubeconfig produces a loadable kubeconfig for the read-only context", () => {
  const text = renderKubeconfig(input());
  // deno-lint-ignore no-explicit-any
  const doc = parseYaml(text) as any;
  assertEquals(doc.apiVersion, "v1");
  assertEquals(doc.kind, "Config");
  assertEquals(doc["current-context"], "homelab-readonly");
  assertEquals(doc.clusters, [{
    name: "homelab-readonly",
    cluster: { server: "https://tailscale-operator-homelab.tail1234.ts.net" },
  }]);
  assertEquals(doc.contexts[0].context, {
    cluster: "homelab-readonly",
    user: "agent-readonly",
    namespace: "argocd",
  });
  assertEquals(doc.users, [{ name: "agent-readonly", user: { token: TOKEN } }]);
  assert(
    text.startsWith("# Generated by scripts/prod-readonly.ts"),
    "header comment first",
  );
  assert(
    !text.includes("certificate-authority"),
    "the proxy uses a publicly trusted certificate",
  );
});

Deno.test("kubeconfigPreview never contains the token", () => {
  const preview = kubeconfigPreview(input());
  assert(
    !preview.includes(TOKEN),
    "the dry-run preview must not leak the token",
  );
  assert(preview.includes(REDACTED));
  // deno-lint-ignore no-explicit-any
  const doc = parseYaml(preview) as any;
  assertEquals(doc.users[0].user.token, REDACTED);
});

Deno.test("redact replaces every occurrence and ignores empty secrets", () => {
  assertEquals(
    redact(`a ${TOKEN} b ${TOKEN}`, [TOKEN]),
    `a ${REDACTED} b ${REDACTED}`,
  );
  assertEquals(redact("nothing to hide", [""]), "nothing to hide");
});

Deno.test("checkToken accepts a JWT and never echoes a bad one", () => {
  assertEquals(checkToken(`  ${TOKEN}\n`, DEFAULT_TOKEN_REF), TOKEN);
  const secretish = "not-a-jwt-but-secret";
  const err = assertThrows(
    () => checkToken(secretish, DEFAULT_TOKEN_REF),
    Error,
  );
  assert(
    !err.message.includes(secretish),
    "the error must not contain the value",
  );
  assertThrows(() => checkToken("   ", DEFAULT_TOKEN_REF), Error, "is empty");
});

Deno.test("tailnetDomain and proxyServerUrl", () => {
  assertEquals(tailnetDomain("tail1234"), "tail1234.ts.net");
  assertEquals(tailnetDomain("Tail1234.ts.net."), "tail1234.ts.net");
  assertEquals(
    proxyServerUrl(DEFAULT_HOSTNAME, "tail1234"),
    "https://tailscale-operator-homelab.tail1234.ts.net",
  );
  assertThrows(() => tailnetDomain("bad tailnet"), UsageError);
  assertThrows(
    () => proxyServerUrl("a.b", "tail1234"),
    UsageError,
    "single DNS label",
  );
});

Deno.test("argv never carries a token", () => {
  const diff = argocdDiffCmd("sonarr", "argocd.example.com", "/tmp/x/config");
  assertEquals(diff, [
    "argocd",
    "app",
    "diff",
    "sonarr",
    "--server",
    "argocd.example.com",
    "--grpc-web",
    "--exit-code=false",
    "--config",
    "/tmp/x/config",
  ]);
  assert(
    !diff.some((a) => a.includes("token")),
    "the ArgoCD token travels in ARGOCD_AUTH_TOKEN",
  );

  const status = kubectlStatusCmd("/k.yaml", DEFAULT_CONTEXT, "30s");
  assertEquals(
    status.join(" "),
    "kubectl --kubeconfig /k.yaml --context homelab-readonly --request-timeout 30s get applications.argoproj.io -n argocd -o json",
  );
  for (const verb of ["apply", "create", "delete", "patch", "edit", "sync"]) {
    assert(
      !status.includes(verb) && !diff.includes(verb),
      `no ${verb} in a read-only command`,
    );
  }
});

Deno.test("domainFromEnvFile reads DOMAIN and ignores placeholders", () => {
  assertEquals(
    domainFromEnvFile("DOMAIN: lab.example.org\nGATEWAY_IP: 1.2.3.4\n"),
    "lab.example.org",
  );
  assertEquals(domainFromEnvFile("DOMAIN: REPLACEME-domain.com\n"), null);
  assertEquals(domainFromEnvFile("OTHER: x\n"), null);
  assertEquals(domainFromEnvFile(": not yaml ["), null);
});

Deno.test("statusRows sorts, shortens revisions and tolerates missing fields", () => {
  const rows = statusRows({
    items: [
      {
        metadata: { name: "plex" },
        status: {
          sync: { status: "Synced", revision: "0123456789abcdef" },
          health: { status: "Degraded" },
          operationState: { phase: "Succeeded" },
        },
      },
      {
        metadata: { name: "cilium" },
        status: {
          sync: { status: "Synced", revision: "fedcba9876543210" },
          health: { status: "Healthy" },
          operationState: { phase: "Succeeded" },
        },
      },
      { metadata: { name: "bare" } },
    ],
  });
  assertEquals(rows.map((r) => r.name), ["bare", "cilium", "plex"]);
  assertEquals(rows[1], {
    name: "cilium",
    sync: "Synced",
    health: "Healthy",
    operation: "Succeeded",
    revision: "fedcba9",
  });
  assertEquals(rows[0], {
    name: "bare",
    sync: "-",
    health: "-",
    operation: "-",
    revision: "-",
  });
  assertEquals(rows.map(isRowHealthy), [false, true, false]);
  assertEquals(statusRows({}), []);
});

Deno.test("formatTable aligns columns", () => {
  assertEquals(
    formatTable(["A", "BB"], [["xyz", "1"], ["q", "22"]]),
    "A    BB\nxyz  1\nq    22",
  );
});

Deno.test("parseArgs defaults", () => {
  const args = parseArgs(["kubeconfig"], ENV);
  assertEquals(args.command, "kubeconfig");
  assertEquals(args.kubeconfig, defaultKubeconfigPath("/home/agent"));
  assertEquals(args.kubeconfig, "/home/agent/.kube/homelab-readonly.yaml");
  assertEquals(args.context, "homelab-readonly");
  assertEquals(args.hostname, DEFAULT_HOSTNAME);
  assertEquals(args.tokenRef, DEFAULT_TOKEN_REF);
  assertEquals(args.argocdTokenRef, DEFAULT_ARGOCD_TOKEN_REF);
  assertEquals(args.dryRun, false);
  assertEquals(parseArgs([], ENV).command, "help");
  assertEquals(parseArgs(["status", "--help"], ENV).command, "help");
});

Deno.test("parseArgs flags, env defaults and the diff app", () => {
  const args = parseArgs(
    [
      "--",
      "diff",
      "sonarr",
      "--argocd-server=argocd.lab.test",
      "--dry-run",
      "--request-timeout",
      "10s",
    ],
    { ...ENV, tailnet: "tail9" },
  );
  assertEquals(args.command, "diff");
  assertEquals(args.app, "sonarr");
  assertEquals(args.argocdServer, "argocd.lab.test");
  assertEquals(args.dryRun, true);
  assertEquals(args.requestTimeout, "10s");
  assertEquals(args.tailnet, "tail9");
  assertEquals(
    parseArgs(["status"], { ...ENV, argocdServer: "argocd.env.test" })
      .argocdServer,
    "argocd.env.test",
  );
});

Deno.test("parseArgs rejects bad invocations", () => {
  const bad: [string[], string][] = [
    [["frobnicate"], "unknown subcommand"],
    [["diff"], "exactly one Application"],
    [["diff", "a", "b"], "exactly one Application"],
    [["diff", "Not_An_App"], "invalid Application name"],
    [["status", "extra"], "unexpected argument"],
    [["status", "--bogus"], "unknown flag"],
    [["kubeconfig", "--tailnet"], "needs a value"],
    [["kubeconfig", "--token-ref", "plain-value"], "1Password reference"],
    [["kubeconfig", "--server", "http://insecure"], "https://"],
    [["status", "--context", "kind-homelab-localdev"], "Kind context"],
    [["status", "--request-timeout", "forever"], "--request-timeout"],
    [
      ["kubeconfig", "--kubeconfig", "/home/agent/.kube/config"],
      "refusing to write",
    ],
  ];
  for (const [argv, msg] of bad) {
    assertThrows(() => parseArgs(argv, ENV), UsageError, msg);
  }
});

Deno.test("isMainKubeconfig only matches ~/.kube/config", () => {
  assert(isMainKubeconfig("/home/agent/.kube/config", "/home/agent"));
  assert(isMainKubeconfig("/home/agent/.kube/../.kube/config", "/home/agent"));
  assert(
    !isMainKubeconfig("/home/agent/.kube/homelab-readonly.yaml", "/home/agent"),
  );
});
