---
# Ansible Galaxy requirements for homelab configuration
# Using Git sources for reliability (Galaxy API can be unreliable)

collections:
  - name: https://github.com/ansible-collections/community.general.git
    type: git
  - name: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: https://github.com/ansible-collections/community.crypto.git
    type: git
