namespace: media
volumes:
  - pvcName: sonarr-config
    pvName: sonarr-config-pv
    volumeHandle: sonarr-config
    storageClassName: democratic-csi-iscsi-hdd
    size: 10Gi
    csi:
      driver: org.democratic-csi.iscsi-hdd
      fsType: ext4
      volumeAttributes:
        node_attach_driver: iscsi
        portal: "172.16.100.150:3260"
        portals: ""
        iqn: "iqn.2005-10.org.freenas.ctl:csi-sonarr-config-homelab"
        lun: "0"
        interface: ""
