# external-dns-config homelab values

cloudflare:
  enabled: true
  namespace: external-dns
  onePasswordItemPath: "vaults/homelab/items/cloudflare"

unifi:
  enabled: true
  namespace: external-dns-unifi
  onePasswordItemPath: "vaults/homelab/items/unifi"
