{{- if (index .Values "kube-prometheus-stack").enabled }}
---
# Prometheus Config: deploys static PV+PVC for Prometheus and Alertmanager (iSCSI)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoUrl }}
    targetRevision: {{ .Values.global.targetRevision }}
    path: charts/prometheus-config
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.global.environment }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ (index .Values "kube-prometheus-stack").namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
{{- end }}
