# traefik-config homelab values

global:
  domain: ryanmcafee.com

namespace: traefik

cloudflare:
  enabled: true
  onePasswordItemPath: "vaults/homelab/items/cloudflare"

dashboard:
  enabled: true
  host: traefik.ryanmcafee.com
  staticIP: "172.16.100.200"

oidc:
  enabled: true
  host: auth.ryanmcafee.com
  providerURL: https://accounts.google.com
  callbackURL: https://auth.ryanmcafee.com/oauth2/callback
  logoutURL: https://auth.ryanmcafee.com/oauth2/logout
  googleOAuthPath: "vaults/homelab/items/google-oauth"
  sessionKeyPath: "vaults/homelab/items/oidc-session-key"
  scopes:
    - openid
    - email
    - profile
  allowedDomains:
    - ryanmcafee.com
